# openapi2-functions.yaml

swagger: '2.0'

info:

  title: fates-api 

  description: Fates API on API Gateway with a Google Cloud Functions backend

  version: 1.0.0

schemes:

  - https

produces:

  - application/json

basePath: /v1

tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:

  /optimize:
  
    post:

      tags:
      - developers

      summary: submit params as input and receive output

      operationId: runOptimize

      description: Performs the optimization function over parameters

      x-google-backend:

        address: https://us-central1-fates-ai-dev.cloudfunctions.net/optimize

      consumes:
      - application/json

      produces:
      - application/json

      parameters:

      - in: body
        name: buildParams
        description: Parameters for building an optimized model
        schema:
          $ref: '#/definitions/BuildParams'

      responses:
        201:
          description: model optimized
          schema:
            $ref: '#/definitions/OptResults'
        400:
          description: invalid input, object invalid
        401:
          description: optimization error
          schema:
            $ref: '#/definitions/DefaultError'
            
    options:
      operationId: corsOptimize
      x-google-backend:
        address: https://us-central1-fates-ai-dev.cloudfunctions.net/optimize
      responses:
        '200':
          description: A successful response

definitions:

  ModelData:
  
    title: The Model Data
    description: data consituting a marketing model
    type: object
    
    properties:

      spend:
        description: dollar value of target total ad spend
        type: number
  
      revenue:
        description: dollar value of target revenue
        type: number
  
      aov:
        description: average order value
        type: number
  
      cogs:
        description: the average cost of goods sold per order
        type: number
  
      contributionMargin:
        description: dollar value of the resultant contribution margin given fees
        type: number
  
      grossMargin:
        description: the dollar value of the gross margin given fees
        type: number
  
      scalePct:
        description: the percentage change in target ad spend from previous period
        type: number
  
      roas:
        description: the target return on ad spend
        type: number
  
      breakevenRoas:
        description: the return on ad spend required for break even given all other variables are fixed
        type: number
  
      roasPctDifference:
        description: the percentage difference between the target return on ad spend and the breakeven return on ad spend
        type: number
  
      purchases:
        description: total target purchases
        type: number
  
      totalCogs:
        description: total dollar value of the cost to produce the sold goods
        type: number
  
      cpa:
        description: the target cost per acquisition
        type: number
  
      fee:
        description: the fixed fee applied to the given time span
        type: number
  
      pctFee:
        description: a variable fee derived from total revenue or spend for the given time span
    
  BuildParams:

    title: Model Parameters

    description: A set of parameters to use when building a model

    type: object

    properties:

      initialSpend:
        description: The dollar value of spend during the initial period
        type: number
        minimum: 0
        exclusiveMinimum: true

      initialRoas:
        description: The ROAS attained during the initial period
        type: number
        minimum: 0
        exclusiveMinimum: true

      fee:
        description: A fixed cost 'fee' applied to each period
        type: number

      pctFeeBasistFee:
        description: A variable cost applied to each period
        type: number
        minimum: 0
        exclusiveMinimum: true
        maximum: 100

      pctFeeBasis:
        description: Specification of percent fee (revenue/spend)
        type: string
        enum:
        - revenue
        - spend

      rowParams:
        type: array

        items:
          type: object
          properties:

            objective:
              description: The objective function to be performed
              type: string
              enum:
              - maxRevenue
              - maxContributionMargin

            lossThreshold:
              description: Adjustment from 0 when root finding for maxRevenue objective
              type: number

            improvementFactor:
              description: A percentage increase to sales volume
              type: number
              minimum: 0
              maximum: 100

            seasonalityFactor:
              description: A percentage increase to sales volume
              type: number
              minimum: 0
              maximum: 100

            negativeSeasonalityFactor:
              description: A percentage increase to sales volume
              type: number
              minimum: 0
              maximum: 100

            aov:
              description: The average order value over a period
              type: number
              minimum: 0
              exclusiveMinimum: true

            cogs:
              description: The average cost of goods sold over a period
              type: number
              minimum: 0
              exclusiveMinimum: True

    required:
    - initialSpend

  OptResults:

    title: Optimization Results / Model Data

    description: Output of the optimization

    type: object

    properties:

      timeSpans:
        type: array
        
        items:
          $ref: '#/definitions/ModelData'

      totals:
        descirption: Totals for the optimization results data
        schema:
          $ref: '#/definitions/ModelData'
          
  DefaultError:
  
    title: Default error response
  
    type: object
    
    properties:
    
      timestamp:
        description: UTC timestamp of error
        type: string
        
      status:
        description: Error status code
        type: string
            
      error:
        description: Error identifier
        type: string

      message:
        description: Human readable and displayable text
        type: string
        
      devMessage:
        description: Developer friendly error message
        type: string

      help:
        description: URL for additional help and documentation on error
        type: string
              
      instance:
        type: string
