---
swagger: "2.0"
info:
  description: Backend API for The Fates optimization tools
  version: 1.0.0
  title: Fates API
basePath: /v1
tags:
- name: optimize
  description: Marketing model optimization
- name: testBudget
  description: Test budget calculator
consumes:
- application/json
produces:
- application/json
paths:
  /optimize/:
    post:
      tags:
      - optimize
      summary: Perform model optimization
      operationId: post_optimize
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/OptParams'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/OptResults'
        "400":
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/DefaultError'
  /testBudget/:
    post:
      tags:
      - testBudget
      operationId: post_test_budget
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/TestBudgetParams'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/TestBudgetResults'
        "400":
          description: BAD REQUEST
          schema:
            $ref: '#/definitions/DefaultError'
definitions:
  OptParams:
    type: object
    properties:
      initialSpend:
        type: number
        example: 5000.0
        description: The dollar value of spend during the initial period
        minimum: 0
        exclusiveMinimum: true
      initialRoas:
        type: number
        example: 3.0
        description: The ROAS attained during the initial period
        minimum: 0
        exclusiveMinimum: true
      fee:
        type: number
        example: 1000.0
        description: A fixed cost fee applied to each period
        minimum: 0
      pctFee:
        type: number
        example: 4.0
        description: A variable cost applied to each period
        minimum: 0
      pctFeeBasis:
        type: string
        example: revenue
        description: Specification of percent fee
        enum:
        - revenue
        - spend
      attributionLoss:
        type: number
        description: Estimated percentage loss of revenue due to attribution
        minimum: 0
        exclusiveMinimum: true
      timeSpans:
        type: array
        items:
          $ref: '#/definitions/OptParamsTimeSpans'
  OptParamsTimeSpans:
    type: object
    properties:
      objective:
        type: string
        example: maxContributionMargin
        description: Objective
        enum:
        - maxRevenue
        - maxContributionMargin
      descaleLimit:
        type: number
        example: 20.0
        description: A limit imposed on the percentage of descale suggested by the model
        minimum: 0
        maximum: 50
      lossThreshold:
        type: number
        description: Minimum desired contribution margin when optimizing on revenue
      improvementFactor:
        type: number
        example: 5.0
        description: A percentage increase to sales volume
        minimum: 0
        maximum: 1000
      seasonalityFactor:
        type: number
        example: 25.0
        description: A percentage increase to sales volume
        minimum: 0
        maximum: 100
      negativeSeasonalityFactor:
        type: number
        description: A percentage decrease to sales volume
        minimum: 0
        maximum: 100
      aov:
        type: number
        example: 50.0
        description: The average order value over a period
        minimum: 0
        exclusiveMinimum: true
      cogs:
        type: number
        example: 10.0
        description: The average cost of goods sold over a period
        minimum: 0
        exclusiveMinimum: true
  DefaultError:
    type: object
    properties:
      timestamp:
        type: string
        format: date-time
        description: UTC formatted timestamp of error
      status:
        type: integer
        example: 400
        description: Error status code
      error:
        type: string
        example: InvalidAPIRequest
        description: Error identifier
      message:
        type: string
        example: Uh oh! Something went wrong.
        description: User friendly error message
      devMessage:
        type: string
        description: Developer friendly error message
      help:
        type: string
        example: See app.fates.ai/api/v1/docs/optimize
        description: URL for additional help and documentation regarding error
  OptResults:
    type: object
    properties:
      months:
        type: array
        items:
          $ref: '#/definitions/OptimizationData'
      totals:
        $ref: '#/definitions/OptimizationData'
  OptimizationData:
    type: object
    properties:
      spend:
        type: number
        example: 5918.0
        description: The dollar value of target total ad spend
      revenue:
        type: number
        example: 16289.0
        description: The dollar amount of target revenue
      aov:
        type: number
        example: 50.0
        description: Average order value
      cogs:
        type: number
        example: 10.0
        description: The average cost of goods sold per order
      contributionMargin:
        type: number
        example: 5961.0
        description: The dollar value of the resulting contribution margin
      grossMargin:
        type: number
        example: 4910.0
        description: The dollar value of the gross margin
      scalePct:
        type: number
        example: 18.37
        description: The percentage change in target ad spend from previous period
      roas:
        type: number
        example: 2.75
        description: The target return on ad spend
      breakevenRoas:
        type: number
        example: 1.43
        description: The return on ad spend required for break even given all other variables are fixed
      purchases:
        type: number
        example: 326.0
        description: Total target purchases
      totalCogs:
        type: number
        example: 3257.0
        description: Total dollar value of the cost to produce the goods sold
      cpa:
        type: number
        example: 18.0
        description: The target cost per acquisition
      fee:
        type: number
        example: 500.0
        description: The fixed fee applied to the given time span
      pctFee:
        type: number
        example: 4.0
        description: The variable fee derived from total revenue or spend for the given time span
  TestBudgetParams:
    type: object
    properties:
      campaignSpend:
        type: number
        example: 20000.0
        description: Total amount of ad spend in nDays
        minimum: 0
        exclusiveMinimum: true
      campaignDailyBudget:
        type: number
        example: 1500.0
        description: Daily total amount of ad spend budgeted for campaign
        minimum: 0
        exclusiveMinimum: true
      testAdDailyBudget:
        type: number
        example: 100.0
        description: Daily total amount of ad spend budgeted for a test ad
        minimum: 0
        exclusiveMinimum: true
      nDays:
        type: integer
        example: 25
        description: Number of days the campaign has so far this month
        minimum: 0
        maximum: 30
        exclusiveMinimum: true
      campaignPurchases:
        type: integer
        example: 110
        description: Total number of purchases gained in campaign so far this month
        minimum: 0
      CPATarget:
        type: number
        example: 220.0
        description: The goal cost per acquisition
        minimum: 0
        exclusiveMinimum: true
      daysLeft:
        type: integer
        example: 5
        description: How many days are left in the month
        minimum: 0
        maximum: 30
        exclusiveMinimum: true
  TestBudgetResults:
    type: object
    properties:
      testBudget:
        type: number
        example: 2050.0
        description: "The total amount allocation for test budget during {daysLeft}"
      testCPA:
        type: number
        example: 300.0
        description: The required CPA for test ads with budget allocation as given in testBudget field
      nonTestCPA:
        type: number
        example: 181.0
        description: The required CPA for non test ads with budget allocation as given in testBudget field
      numberAds:
        type: integer
        example: 4
        description: The estimated number of test ads that may be launched
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
